# Generated by Django 4.2.7 on 2023-12-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_report', '0004_report_bug_report_floating_defect_report_id_tfs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='floating_defect',
            field=models.BooleanField(default=False),
        ),
    ]
