# Generated by Django 4.2.7 on 2023-12-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_report', '0008_alter_report_platform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_create',
            field=models.DateField(),
        ),
    ]
